20241229 Added create_site service to compose.knimer.yaml

diff --git a/compose.knimer.yaml b/compose.knimer.yaml
--- a/compose.knimer.yaml
+++ b/compose.knimer.yaml
@@ -54,6 +54,43 @@ services:
     <<: *backend_defaults
     platform: ${PLATFORM}
 
+  create-site:
+    image: ${CUSTOM_IMAGE}:${CUSTOM_TAG}
+    networks:
+      - frappe_network
+    deploy:
+      restart_policy:
+        condition: unless-stopped
+    depends_on:
+      - backend
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+    entrypoint:
+      - bash
+      - -c
+    command:
+      - >
+        wait-for-it -t 120 $$DB_HOST:$$DB_PORT;
+        wait-for-it -t 120 $$REDIS_CACHE;
+        wait-for-it -t 120 $$REDIS_QUEUE;
+        export start=`date +%s`;
+        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
+        do
+          echo "Waiting for sites/common_site_config.json to be created";
+          sleep 5;
+          if (( `date +%s`-start > 120 )); then
+            echo "could not find sites/common_site_config.json with required keys";
+            exit 1
+          fi
+        done;
+        echo "sites/common_site_config.json found";
+        bench new-site --mariadb-user-host-login-scope='%' --admin-password=$$ADMIN_PASSWORD --db-host $$DB_HOST --db-root-username=root --db-root-password=$$MYSQL_ROOT_PASSWORD --install-app erpnext --set-default $$SITE_NAME;
+        bench --site $$SITE_NAME --install-app $$APPS_TO_INSTALL
+        bench --site $$SITE_NAME set-config host_name $$SITE_NAME
+
   frontend:
     <<: *customizable_image
     platform: ${PLATFORM}
@@ -101,4 +138,3 @@ services:
 # ERPNext requires local assets access (Frappe does not)
 volumes:
   sites:
-  
